export default function Hero() {
  return (
    <section style={styles.hero}>
      {/* Background grid */}
      <div style={styles.grid} aria-hidden="true">
        {Array.from({ length: 80 }).map((_, i) => (
          <div key={i} style={styles.gridCell} />
        ))}
      </div>

      <div style={styles.content}>
        <div style={styles.tag} className="mono">
          <span style={styles.tagDot} />
          STELLAR TESTNET · x402 PROTOCOL LIVE
        </div>

        <h2 style={styles.headline}>
          The internet's first<br />
          <em style={styles.italic}>pay-per-article</em><br />
          AI newsroom.
        </h2>

        <p style={styles.sub}>
          No accounts. No subscriptions. No API keys.<br />
          Pay 1 XLM per article — directly on Stellar blockchain.<br />
          Content generated by Gemini AI, unlocked by your transaction.
        </p>

        <div style={styles.pills}>
          {[
            '⚡ Instant Settlement',
            '💸 $0.00001 Fee',
            '🔒 No Account Needed',
            '✦ Real Stellar Txns',
          ].map(p => (
            <span key={p} style={styles.pill} className="mono">{p}</span>
          ))}
        </div>
      </div>
    </section>
  )
}

const styles = {
  hero: {
    position: 'relative',
    borderBottom: '1px solid #1e1e1e',
    overflow: 'hidden',
    padding: '56px 40px 48px',
  },
  grid: {
    position: 'absolute',
    inset: 0,
    display: 'grid',
    gridTemplateColumns: 'repeat(16, 1fr)',
    opacity: 0.03,
    pointerEvents: 'none',
  },
  gridCell: {
    border: '1px solid #c9a84c',
  },
  content: {
    position: 'relative',
    maxWidth: 680,
    animation: 'fadeUp 0.7s ease',
  },
  tag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 9,
    letterSpacing: '0.2em',
    color: '#c9a84c',
    border: '1px solid #2a2a2a',
    padding: '5px 12px',
    marginBottom: 20,
  },
  tagDot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    background: '#27ae60',
    display: 'inline-block',
    animation: 'pulse-gold 2s infinite',
  },
  headline: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 'clamp(32px, 5vw, 56px)',
    fontWeight: 900,
    lineHeight: 1.1,
    color: '#f0ece4',
    letterSpacing: '-0.02em',
    marginBottom: 20,
  },
  italic: {
    color: '#c9a84c',
    fontStyle: 'italic',
  },
  sub: {
    fontSize: 14,
    lineHeight: 1.7,
    color: '#6b6560',
    marginBottom: 24,
  },
  pills: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    fontSize: 9,
    letterSpacing: '0.1em',
    color: '#4a4a4a',
    border: '1px solid #1e1e1e',
    padding: '4px 10px',
  },
}
